version: 2
updates:
  # Enable version updates for pnpm
  - package-ecosystem: npm
    # Look for `package.json` and `lock` files in the root directory
    directory: /
    # Check the npm registry for updates every week
    schedule:
      interval: weekly
    # Limit the number of open pull requests for version updates to 1
    open-pull-requests-limit: 1
    # Group updates into a single pull request
    groups:
      # The name of the group (identifier)
      pnpm-deps:
        update-types: [minor, patch]
    # Only allow minor and patch updates
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    # Target branch for pull requests
    target-branch: develop

  # Enable version updates for GitHub Actions
  - package-ecosystem: github-actions
    # Look for `.github/workflows` in the root directory
    directory: /
    # Check GitHub Actions for updates every week
    schedule:
      interval: weekly
    # Limit the number of open pull requests for version updates to 1
    open-pull-requests-limit: 1
    # Target branch for pull requests
    target-branch: develop
